import 'package:english_words/english_words.dart';
import 'package:flutter/foundation.dart';
import 'package:roomrai1/models/Transaction.dart';

class TransactionProvider with ChangeNotifier {
  List<Transaction> transactions = [
    Transaction(
      showSearch: "EGR101/Faculity of Engineering",
      codeRoom: "EGR101",
      floor: 1,
      room: 1,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR102/Faculity of Engineering",
      codeRoom: "EGR102",
      floor: 1,
      room: 2,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR103/Faculity of Engineering",
      codeRoom: "EGR103",
      floor: 1,
      room: 3,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR104/Faculity of Engineering",
      codeRoom: "EGR104",
      floor: 1,
      room: 4,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR105/Faculity of Engineering",
      codeRoom: "EGR105",
      floor: 1,
      room: 5,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR106/Faculity of Engineering",
      codeRoom: "EGR106",
      floor: 1,
      room: 6,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR107/Faculity of Engineering",
      codeRoom: "EGR107",
      floor: 1,
      room: 7,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR108/Faculity of Engineering",
      codeRoom: "EGR108",
      floor: 1,
      room: 8,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR109/Faculity of Engineering",
      codeRoom: "EGR109",
      floor: 1,
      room: 9,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR110/Faculity of Engineering",
      codeRoom: "EGR110",
      floor: 1,
      room: 10,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR111/Faculity of Engineering",
      codeRoom: "EGR111",
      floor: 1,
      room: 11,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR112/Faculity of Engineering",
      codeRoom: "EGR112",
      floor: 1,
      room: 12,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR113/Faculity of Engineering",
      codeRoom: "EGR113",
      floor: 1,
      room: 13,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR114/Faculity of Engineering",
      codeRoom: "EGR114",
      floor: 1,
      room: 14,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR115/Faculity of Engineering",
      codeRoom: "EGR115",
      floor: 1,
      room: 15,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR201/Faculity of Engineering",
      codeRoom: "EGR201",
      floor: 2,
      room: 1,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR202/Faculity of Engineering",
      codeRoom: "EGR202",
      floor: 2,
      room: 2,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR203/Faculity of Engineering",
      codeRoom: "EGR203",
      floor: 2,
      room: 3,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR204/Faculity of Engineering",
      codeRoom: "EGR204",
      floor: 2,
      room: 4,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR205/Faculity of Engineering",
      codeRoom: "EGR205",
      floor: 2,
      room: 5,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR206/Faculity of Engineering",
      codeRoom: "EGR206",
      floor: 2,
      room: 6,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR207/Faculity of Engineering",
      codeRoom: "EGR207",
      floor: 2,
      room: 7,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR208/Faculity of Engineering",
      codeRoom: "EGR208",
      floor: 2,
      room: 8,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR209/Faculity of Engineering",
      codeRoom: "EGR209",
      floor: 2,
      room: 9,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR210/Faculity of Engineering",
      codeRoom: "EGR210",
      floor: 2,
      room: 10,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR211/Faculity of Engineering",
      codeRoom: "EGR211",
      floor: 2,
      room: 11,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR212/Faculity of Engineering",
      codeRoom: "EGR212",
      floor: 2,
      room: 12,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR213/Faculity of Engineering",
      codeRoom: "EGR213",
      floor: 2,
      room: 13,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR214/Faculity of Engineering",
      codeRoom: "EGR214",
      floor: 2,
      room: 14,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR215/Faculity of Engineering",
      codeRoom: "EGR215",
      floor: 2,
      room: 15,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR301/Faculity of Engineering",
      codeRoom: "EGR301",
      floor: 3,
      room: 1,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR302/Faculity of Engineering",
      codeRoom: "EGR302",
      floor: 3,
      room: 2,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR303/Faculity of Engineering",
      codeRoom: "EGR303",
      floor: 3,
      room: 3,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR304/Faculity of Engineering",
      codeRoom: "EGR304",
      floor: 3,
      room: 4,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR305/Faculity of Engineering",
      codeRoom: "EGR305",
      floor: 3,
      room: 5,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR306/Faculity of Engineering",
      codeRoom: "EGR306",
      floor: 3,
      room: 6,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR307/Faculity of Engineering",
      codeRoom: "EGR307",
      floor: 3,
      room: 7,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR308/Faculity of Engineering",
      codeRoom: "EGR308",
      floor: 3,
      room: 8,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR309/Faculity of Engineering",
      codeRoom: "EGR309",
      floor: 3,
      room: 9,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR310/Faculity of Engineering",
      codeRoom: "EGR310",
      floor: 3,
      room: 10,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR311/Faculity of Engineering",
      codeRoom: "EGR311",
      floor: 3,
      room: 11,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR312/Faculity of Engineering",
      codeRoom: "EGR312",
      floor: 3,
      room: 12,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR313/Faculity of Engineering",
      codeRoom: "EGR313",
      floor: 3,
      room: 13,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR314/Faculity of Engineering",
      codeRoom: "EGR314",
      floor: 3,
      room: 14,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR315/Faculity of Engineering",
      codeRoom: "EGR315",
      floor: 3,
      room: 15,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR401/Faculity of Engineering",
      codeRoom: "EGR401",
      floor: 4,
      room: 1,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR402/Faculity of Engineering",
      codeRoom: "EGR402",
      floor: 4,
      room: 2,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR403/Faculity of Engineering",
      codeRoom: "EGR403",
      floor: 4,
      room: 3,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR404/Faculity of Engineering",
      codeRoom: "EGR404",
      floor: 4,
      room: 4,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR405/Faculity of Engineering",
      codeRoom: "EGR405",
      floor: 4,
      room: 5,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR406/Faculity of Engineering",
      codeRoom: "EGR406",
      floor: 4,
      room: 6,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR407/Faculity of Engineering",
      codeRoom: "EGR407",
      floor: 4,
      room: 7,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR408/Faculity of Engineering",
      codeRoom: "EGR408",
      floor: 4,
      room: 8,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR409/Faculity of Engineering",
      codeRoom: "EGR409",
      floor: 4,
      room: 9,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR410/Faculity of Engineering",
      codeRoom: "EGR410",
      floor: 4,
      room: 10,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR411/Faculity of Engineering",
      codeRoom: "EGR411",
      floor: 4,
      room: 11,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR412/Faculity of Engineering",
      codeRoom: "EGR412",
      floor: 4,
      room: 12,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR413/Faculity of Engineering",
      codeRoom: "EGR413",
      floor: 4,
      room: 13,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR414/Faculity of Engineering",
      codeRoom: "EGR414",
      floor: 4,
      room: 14,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR415/Faculity of Engineering",
      codeRoom: "EGR415",
      floor: 4,
      room: 15,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR501/Faculity of Engineering",
      codeRoom: "EGR501",
      floor: 5,
      room: 1,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR502/Faculity of Engineering",
      codeRoom: "EGR502",
      floor: 5,
      room: 2,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR503/Faculity of Engineering",
      codeRoom: "EGR503",
      floor: 5,
      room: 3,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR504/Faculity of Engineering",
      codeRoom: "EGR504",
      floor: 5,
      room: 4,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR505/Faculity of Engineering",
      codeRoom: "EGR505",
      floor: 5,
      room: 5,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR506/Faculity of Engineering",
      codeRoom: "EGR506",
      floor: 5,
      room: 6,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR507/Faculity of Engineering",
      codeRoom: "EGR507",
      floor: 5,
      room: 7,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR508/Faculity of Engineering",
      codeRoom: "EGR508",
      floor: 5,
      room: 8,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR509/Faculity of Engineering",
      codeRoom: "EGR509",
      floor: 5,
      room: 9,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR510/Faculity of Engineering",
      codeRoom: "EGR510",
      floor: 5,
      room: 10,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR511/Faculity of Engineering",
      codeRoom: "EGR511",
      floor: 5,
      room: 11,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR512/Faculity of Engineering",
      codeRoom: "EGR512",
      floor: 5,
      room: 12,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR513/Faculity of Engineering",
      codeRoom: "EGR513",
      floor: 5,
      room: 13,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR514/Faculity of Engineering",
      codeRoom: "EGR514",
      floor: 5,
      room: 14,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR515/Faculity of Engineering",
      codeRoom: "EGR515",
      floor: 5,
      room: 15,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR601/Faculity of Engineering",
      codeRoom: "EGR601",
      floor: 6,
      room: 1,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR602/Faculity of Engineering",
      codeRoom: "EGR602",
      floor: 6,
      room: 2,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR603/Faculity of Engineering",
      codeRoom: "EGR603",
      floor: 6,
      room: 3,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR604/Faculity of Engineering",
      codeRoom: "EGR604",
      floor: 6,
      room: 4,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR605/Faculity of Engineering",
      codeRoom: "EGR605",
      floor: 6,
      room: 5,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR606/Faculity of Engineering",
      codeRoom: "EGR606",
      floor: 6,
      room: 6,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR607/Faculity of Engineering",
      codeRoom: "EGR607",
      floor: 6,
      room: 7,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR608/Faculity of Engineering",
      codeRoom: "EGR608",
      floor: 6,
      room: 8,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR609/Faculity of Engineering",
      codeRoom: "EGR609",
      floor: 6,
      room: 9,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR610/Faculity of Engineering",
      codeRoom: "EGR610",
      floor: 6,
      room: 10,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR611/Faculity of Engineering",
      codeRoom: "EGR611",
      floor: 6,
      room: 11,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR612/Faculity of Engineering",
      codeRoom: "EGR612",
      floor: 6,
      room: 12,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR613/Faculity of Engineering",
      codeRoom: "EGR613",
      floor: 6,
      room: 13,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR614/Faculity of Engineering",
      codeRoom: "EGR614",
      floor: 6,
      room: 14,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR615/Faculity of Engineering",
      codeRoom: "EGR615",
      floor: 6,
      room: 15,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR701/Faculity of Engineering",
      codeRoom: "EGR701",
      floor: 7,
      room: 1,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR702/Faculity of Engineering",
      codeRoom: "EGR702",
      floor: 7,
      room: 2,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR703/Faculity of Engineering",
      codeRoom: "EGR703",
      floor: 7,
      room: 3,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR704/Faculity of Engineering",
      codeRoom: "EGR704",
      floor: 7,
      room: 4,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR705/Faculity of Engineering",
      codeRoom: "EGR705",
      floor: 7,
      room: 5,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR706/Faculity of Engineering",
      codeRoom: "EGR706",
      floor: 7,
      room: 6,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR707/Faculity of Engineering",
      codeRoom: "EGR707",
      floor: 7,
      room: 7,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR708/Faculity of Engineering",
      codeRoom: "EGR708",
      floor: 7,
      room: 8,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR709/Faculity of Engineering",
      codeRoom: "EGR709",
      floor: 7,
      room: 9,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR710/Faculity of Engineering",
      codeRoom: "EGR710",
      floor: 7,
      room: 10,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR711/Faculity of Engineering",
      codeRoom: "EGR711",
      floor: 7,
      room: 11,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR712/Faculity of Engineering",
      codeRoom: "EGR712",
      floor: 7,
      room: 12,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR713/Faculity of Engineering",
      codeRoom: "EGR713",
      floor: 7,
      room: 13,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR714/Faculity of Engineering",
      codeRoom: "EGR714",
      floor: 7,
      room: 14,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "EGR715/Faculity of Engineering",
      codeRoom: "EGR715",
      floor: 7,
      room: 15,
      building: "Faculity of Engineering",
    ),
    Transaction(
      showSearch: "SC1001/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC1001",
      floor: 1,
      room: 1,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC1002/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC1002",
      floor: 1,
      room: 2,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC1011/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC1011",
      floor: 1,
      room: 11,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC1012/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC1012",
      floor: 1,
      room: 12,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC1013/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC1013",
      floor: 1,
      room: 13,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC1014/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC1014",
      floor: 1,
      room: 14,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC1015/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC1015",
      floor: 1,
      room: 15,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC1016/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC1016",
      floor: 1,
      room: 16,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC1017/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC1017",
      floor: 1,
      room: 17,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC1018/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC1018",
      floor: 1,
      room: 18,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC1019/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC1019",
      floor: 1,
      room: 19,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC1020/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC1020",
      floor: 1,
      room: 20,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC1023/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC1023",
      floor: 1,
      room: 23,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC1024/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC1024",
      floor: 1,
      room: 24,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC1025/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC1025",
      floor: 1,
      room: 25,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC1026/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC1026",
      floor: 1,
      room: 26,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC1035/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC1035",
      floor: 1,
      room: 35,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC1036/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC1036",
      floor: 1,
      room: 36,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC1037/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC1037",
      floor: 1,
      room: 37,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC1038/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC1038",
      floor: 1,
      room: 38,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC1041/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC1041",
      floor: 1,
      room: 41,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC1042/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC1042",
      floor: 1,
      room: 42,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC1043/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC1043",
      floor: 1,
      room: 43,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC1044/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC1044",
      floor: 1,
      room: 44,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC1045/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC1045",
      floor: 1,
      room: 45,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC1046/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC1046",
      floor: 1,
      room: 46,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC1047/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC1047",
      floor: 1,
      room: 47,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC1048/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC1048",
      floor: 1,
      room: 48,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC1049/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC1049",
      floor: 1,
      room: 49,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC1050/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC1050",
      floor: 1,
      room: 50,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC1058/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC1058",
      floor: 1,
      room: 58,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC1059/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC1059",
      floor: 1,
      room: 59,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC1062/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC1062",
      floor: 1,
      room: 62,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC1063/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC1063",
      floor: 1,
      room: 63,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC1064/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC1064",
      floor: 1,
      room: 64,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC1065/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC1065",
      floor: 1,
      room: 65,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC1066/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC1066",
      floor: 1,
      room: 66,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC1067/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC1067",
      floor: 1,
      room: 67,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC1068/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC1068",
      floor: 1,
      room: 68,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC1069/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC1069",
      floor: 1,
      room: 69,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2001/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2001",
      floor: 2,
      room: 1,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2002/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2002",
      floor: 2,
      room: 2,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2003/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2003",
      floor: 2,
      room: 3,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2004/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2004",
      floor: 2,
      room: 4,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2005/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2005",
      floor: 2,
      room: 5,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2006/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2006",
      floor: 2,
      room: 6,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2007/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2007",
      floor: 2,
      room: 7,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2008/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2008",
      floor: 2,
      room: 8,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2009/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2009",
      floor: 2,
      room: 9,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2010/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2010",
      floor: 2,
      room: 10,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2013/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2013",
      floor: 2,
      room: 13,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2014/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2014",
      floor: 2,
      room: 14,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2015/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2015",
      floor: 2,
      room: 15,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2016/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2016",
      floor: 2,
      room: 16,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2025/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2025",
      floor: 2,
      room: 25,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2026/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2026",
      floor: 2,
      room: 26,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2027/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2027",
      floor: 2,
      room: 27,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2028/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2028",
      floor: 2,
      room: 28,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2031/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2031",
      floor: 2,
      room: 31,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2032/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2032",
      floor: 2,
      room: 32,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2033/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2033",
      floor: 2,
      room: 33,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2034/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2034",
      floor: 2,
      room: 34,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2035/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2035",
      floor: 2,
      room: 35,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2036/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2036",
      floor: 2,
      room: 36,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2037/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2037",
      floor: 2,
      room: 37,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2038/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2038",
      floor: 2,
      room: 38,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2039/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2039",
      floor: 2,
      room: 39,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2040/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2040",
      floor: 2,
      room: 40,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2041/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2041",
      floor: 2,
      room: 41,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2042/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2042",
      floor: 2,
      room: 42,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2043/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2043",
      floor: 2,
      room: 43,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2044/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2044",
      floor: 2,
      room: 44,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2047/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2047",
      floor: 2,
      room: 47,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2048/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2048",
      floor: 2,
      room: 48,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2049/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2049",
      floor: 2,
      room: 49,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2050/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2050",
      floor: 2,
      room: 50,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2051/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2051",
      floor: 2,
      room: 51,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2052/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2052",
      floor: 2,
      room: 52,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2053/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2053",
      floor: 2,
      room: 53,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2054/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2054",
      floor: 2,
      room: 54,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2055/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2055",
      floor: 2,
      room: 55,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2056/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2056",
      floor: 2,
      room: 56,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2059/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2059",
      floor: 2,
      room: 59,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2060/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2060",
      floor: 2,
      room: 60,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2061/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2061",
      floor: 2,
      room: 61,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC2062/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC2062",
      floor: 2,
      room: 62,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC3004/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC3004",
      floor: 3,
      room: 4,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC3005/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC3005",
      floor: 3,
      room: 5,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC3006/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC3006",
      floor: 3,
      room: 6,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC3010/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC3010",
      floor: 3,
      room: 10,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC3011/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC3011",
      floor: 3,
      room: 11,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC3012/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC3012",
      floor: 3,
      room: 12,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC3015/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC3015",
      floor: 3,
      room: 15,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC3016/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC3016",
      floor: 3,
      room: 16,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC3017/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC3017",
      floor: 3,
      room: 17,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC3018/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC3018",
      floor: 3,
      room: 18,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC3019/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC3019",
      floor: 3,
      room: 19,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC3020/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC3020",
      floor: 3,
      room: 20,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC3029/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC3029",
      floor: 3,
      room: 29,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC3030/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC3030",
      floor: 3,
      room: 30,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC3031/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC3031",
      floor: 3,
      room: 31,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC3032/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC3032",
      floor: 3,
      room: 32,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC3033/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC3033",
      floor: 3,
      room: 33,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC3034/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC3034",
      floor: 3,
      room: 34,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC3037/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC3037",
      floor: 3,
      room: 37,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC3038/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC3038",
      floor: 3,
      room: 38,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC3039/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC3039",
      floor: 3,
      room: 39,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC3040/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC3040",
      floor: 3,
      room: 40,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC3041/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC3041",
      floor: 3,
      room: 41,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC3042/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC3042",
      floor: 3,
      room: 42,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC3043/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC3043",
      floor: 3,
      room: 43,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC3046/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC3046",
      floor: 3,
      room: 46,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC3047/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC3047",
      floor: 3,
      room: 47,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC3048/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC3048",
      floor: 3,
      room: 48,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC3049/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC3049",
      floor: 3,
      room: 49,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC3050/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC3050",
      floor: 3,
      room: 50,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC3051/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC3051",
      floor: 3,
      room: 51,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC3052/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC3052",
      floor: 3,
      room: 52,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC3053/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC3053",
      floor: 3,
      room: 53,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC3056/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC3056",
      floor: 3,
      room: 56,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC3057/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC3057",
      floor: 3,
      room: 57,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC3058/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC3058",
      floor: 3,
      room: 58,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC3059/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC3059",
      floor: 3,
      room: 59,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC4001/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC4001",
      floor: 4,
      room: 1,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC4004/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC4004",
      floor: 4,
      room: 4,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC4005/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC4005",
      floor: 4,
      room: 5,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC4006/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC4006",
      floor: 4,
      room: 6,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC4009/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC4009",
      floor: 4,
      room: 9,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC4010/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC4010",
      floor: 4,
      room: 10,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC4011/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC4011",
      floor: 4,
      room: 11,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC4020/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC4020",
      floor: 4,
      room: 20,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC4023/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC4023",
      floor: 4,
      room: 23,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC4024/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC4024",
      floor: 4,
      room: 24,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC4025/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC4025",
      floor: 4,
      room: 25,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC4028/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC4028",
      floor: 4,
      room: 28,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC4029/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC4029",
      floor: 4,
      room: 29,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC4030/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC4030",
      floor: 4,
      room: 30,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC4031/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC4031",
      floor: 4,
      room: 31,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC4032/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC4032",
      floor: 4,
      room: 32,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC4035/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC4035",
      floor: 4,
      room: 35,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC4036/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC4036",
      floor: 4,
      room: 36,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC4037/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC4037",
      floor: 4,
      room: 37,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC4038/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC4038",
      floor: 4,
      room: 38,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC4039/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC4039",
      floor: 4,
      room: 39,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC4040/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC4040",
      floor: 4,
      room: 40,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC4043/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC4043",
      floor: 4,
      room: 43,
      building: "Social Sciences Building Complex or SC buildings",
    ),
    Transaction(
      showSearch: "SC4044/Social Sciences Building Complex or SC buildings",
      codeRoom: "SC4044",
      floor: 4,
      room: 44,
      building: "Social Sciences Building Complex or SC buildings",
    ),
  ];
}
